<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="ViewModel\Ignored\**" />
    <EmbeddedResource Remove="ViewModel\Ignored\**" />
    <None Remove="ViewModel\Ignored\**" />
    <Page Remove="ViewModel\Ignored\**" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="Images\room1.png" />
    <None Remove="Images\room2.png" />
    <None Remove="Images\room3.png" />
    <None Remove="Images\room4.png" />
    <None Remove="Images\userProfile.png" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Costura.Fody" Version="6.0.0">
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="MahApps.Metro.IconPacks" Version="6.2.1" />
    <PackageReference Include="MaterialDesignThemes" Version="5.3.0" />
    <PackageReference Include="Microsoft.Data.SqlClient" Version="5.2.2" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.10" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="9.0.10" />
    <PackageReference Include="Microsoft.Extensions.Logging" Version="9.0.10" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Images\room1.png" />
    <Resource Include="Images\room2.png" />
    <Resource Include="Images\room3.png" />
    <Resource Include="Images\room4.png" />
    <Resource Include="Images\userProfile.png" />
  </ItemGroup>

  <ItemGroup>
    <None Update="config.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
