name: FinalProject Build

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    name: Build
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v3.3.0

      - name: Setup MS Build
        uses: microsoft/setup-msbuild@v1.1.3
        
      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1.1.1
     
      - name: Restore NuGet Packages
        run: nuget restore PinusPengger.sln
        
      - name: Create app.config file
        run: echo "${{ secrets.APP_CONFIG }}" | cat > App.config
      
      - name: Build Release Library
        run:  msbuild PinusPengger.sln /p:Configuration=Release
        
      - name: Get current time
        uses: josStorer/get-current-time@v2.0.2
        id: current-time
        with:
          format: YYYYMMDD-HHmmss
          utcOffset: "+07:00"
                
      - name: Upload Artifact
        uses: actions/upload-artifact@v3.1.2
        with:
          name: FinalProject_${{ steps.current-time.outputs.formattedTime }}
          path: ./bin/Release/net6.0-windows
          retention-days: 10
